### ISSUE TITLE
add_lead_in_out IndexError: list index out of range

### ISSUE THREAD

**Issue by AndyEveritt** [AndyEveritt/ASMBL#45]
https://forum.e3d-online.com/threads/asbml-fusion-plugin-post-script-not-workingdi.3983/

# Issue

Spliting subtractive gcode layers...
Traceback (most recent call last):
File "main.py", line 26, in <module>
asmbl_parser = Parser(args.config)
File "src\ASMBL_parser.py", line 34, in __init__
self.main()
File "src\ASMBL_parser.py", line 63, in main
operations = self.split_cam_operations(self.gcode_sub)
File "src\ASMBL_parser.py", line 216, in split_cam_operations
operation_layers = self.group_cam_segments(segments, name, strategy, tool)
File "src\ASMBL_parser.py", line 196, in group_cam_segments
layer_group = self.add_lead_in_out(segments, cutting_group)
File "src\ASMBL_parser.py", line 165, in add_lead_in_out
if segments[post_index].type == 'lead out':
IndexError: list index out of range
[20296] Failed to execute script main

# Version
ASMBL-2.3.4.exe

**Comment by AndyEveritt** [comment]
[tmp.zip](https://github.com/AndyEveritt/ASMBL/files/5917331/tmp.zip)

**Comment by AndyEveritt** [comment]
Have reproduced the error
